import type { NavItem, SkillCategory, ProjectCategory, Experience, Skill, Project, Profile } from '@/types';

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Experience', href: '/experience' },
  { label: 'Skills', href: '/skills' },
  { label: 'Projects', href: '/projects' },
  { label: 'Resume', href: '/resume' },
  { label: 'Contact', href: '/contact' },
];

export const ADMIN_NAV_ITEMS: NavItem[] = [
  { label: 'Dashboard', href: '/admin' },
  { label: 'Profile', href: '/admin/profile' },
  { label: 'Experience', href: '/admin/experience' },
  { label: 'Skills', href: '/admin/skills' },
  { label: 'Projects', href: '/admin/projects' },
  { label: 'Resume', href: '/admin/resume' },
  { label: 'SEO', href: '/admin/seo' },
  { label: 'Settings', href: '/admin/settings' },
];

export const SKILL_CATEGORIES: { value: SkillCategory; label: string; icon: string }[] = [
  { value: 'data-analytics', label: 'Data & Analytics', icon: 'database' },
  { value: 'web-development', label: 'Web Development', icon: 'code' },
  { value: 'ai-automation', label: 'AI & Automation', icon: 'cpu' },
  { value: 'creative-technology', label: 'Creative Technology', icon: 'palette' },
];

export const PROJECT_CATEGORIES: { value: ProjectCategory; label: string; icon: string }[] = [
  { value: 'data-analytics', label: 'Data Analytics', icon: 'bar-chart' },
  { value: 'ai-automation', label: 'AI & Automation', icon: 'zap' },
  { value: 'web-applications', label: 'Web Applications', icon: 'layout' },
  { value: 'creative-technology', label: 'Creative Technology', icon: 'image' },
];

export const PROFICIENCY_LEVELS = [
  { value: 'core', label: 'Core' },
  { value: 'applied', label: 'Applied' },
  { value: 'working-knowledge', label: 'Working Knowledge' },
  { value: 'familiar', label: 'Familiar' },
];

export const DEFAULT_PROFILE = {
  name: '[ADD YOUR NAME]',
  headline: 'Assistant Manager | Data Analytics | AI-Enabled Business Solutions',
  heroDescription: 'Assistant Manager with 2+ years of professional experience, combining business understanding, data analytics, AI-assisted workflows and modern technology to solve practical problems.',
  about: 'I turn business problems into practical solutions using data, AI and modern technology. With 2+ years of experience as an Assistant Manager at Dhuri Na Venture Private Limited, I combine business understanding, data analytics, AI-assisted workflows, and modern technology to solve practical problems.\n\nMy journey from MAS Educative to Assistant Manager has been defined by continuous learning and practical application. I work with Python, SQL, Power BI, and Excel for data analysis; build web applications with Next.js, React, Supabase, and PostgreSQL; and leverage AI to accelerate research, analysis, development, and creative workflows.\n\nI focus on solving the underlying business problem rather than simply using technology. Whether it\'s building a dashboard that drives decisions, automating a repetitive workflow, or developing a web application that streamlines operations, my approach is always: understand the problem first, then apply the right tools.',
  location: '[ADD YOUR LOCATION]',
  email: '[ADD YOUR EMAIL]',
  phone: '[ADD YOUR PHONE]',
  linkedin: '[ADD YOUR LINKEDIN URL]',
  github: '[ADD YOUR GITHUB URL]',
  openToWork: true,
  ctaText: 'Let\'s Build Something Useful',
};

export const WHAT_I_BRING = [
  {
    title: 'Business Understanding',
    description: 'Understand operational requirements and translate them into practical solutions.',
    icon: 'briefcase',
  },
  {
    title: 'Data Thinking',
    description: 'Use Excel, SQL, Python and Power BI to analyze and communicate data.',
    icon: 'bar-chart-2',
  },
  {
    title: 'AI-Enabled Productivity',
    description: 'Use AI to accelerate research, analysis, development and creative workflows.',
    icon: 'cpu',
  },
  {
    title: 'Technology Execution',
    description: 'Build practical web applications using modern technologies.',
    icon: 'code',
  },
  {
    title: 'Problem Solving',
    description: 'Focus on solving the underlying business problem rather than simply using technology.',
    icon: 'puzzle',
  },
];

export const CAREER_JOURNEY = [
  {
    role: 'Assistant Manager',
    company: 'Dhuri Na Venture Private Limited',
    period: '2+ Years',
    description: 'Data + AI + Technology',
    isCurrent: true,
  },
  {
    role: '[ADD EXACT DESIGNATION]',
    company: 'MAS Educative',
    period: '[ADD DATES]',
    description: 'Professional Foundation',
    isCurrent: false,
  },
];

export const PROFESSIONAL_SNAPSHOT = [
  { label: '2+ Years', value: 'Professional Experience' },
  { label: 'Assistant Manager', value: 'Current Role' },
  { label: 'Data & Analytics', value: 'Core Competency' },
  { label: 'AI-Enabled Workflows', value: 'Productivity Multiplier' },
  { label: 'Web Applications', value: 'Technical Capability' },
];

// ---------------------------------------------------------------------------
// CMS fallbacks: used when Supabase is not configured or tables are empty.
// constants.ts is the ONLY place fallback content lives — components and the
// CMS read layer both import from here. No duplicated copies elsewhere.
// ---------------------------------------------------------------------------

export const FALLBACK_PROFILE: Profile = {
  name: '[ADD YOUR NAME]',
  headline: 'Assistant Manager | Data Analytics | AI-Enabled Business Solutions',
  heroDescription:
    'Assistant Manager with 2+ years of professional experience, combining business understanding, data analytics, AI-assisted workflows and modern technology to solve practical problems.',
  about:
    "I turn business problems into practical solutions using data, AI and modern technology. With 2+ years of experience as an Assistant Manager at Dhuri Na Venture Private Limited, I combine business understanding, data analytics, AI-assisted workflows, and modern technology to solve practical problems.\n\nMy journey from MAS Educative to Assistant Manager has been defined by continuous learning and practical application. I work with Python, SQL, Power BI, and Excel for data analysis; build web applications with Next.js, React, Supabase, and PostgreSQL; and leverage AI to accelerate research, analysis, development, and creative workflows.\n\nI focus on solving the underlying business problem rather than simply using technology. Whether it's building a dashboard that drives decisions, automating a repetitive workflow, or developing a web application that streamlines operations, my approach is always: understand the problem first, then apply the right tools.",
  location: '[ADD YOUR LOCATION]',
  email: '[ADD YOUR EMAIL]',
  phone: '[ADD YOUR PHONE]',
  linkedin: '[ADD YOUR LINKEDIN URL]',
  github: '[ADD YOUR GITHUB URL]',
  openToWork: true,
  ctaText: "Let's Build Something Useful",
  updatedAt: new Date(0).toISOString(),
};

export const FALLBACK_EXPERIENCES: Experience[] = [
  {
    id: 'fallback-exp-1',
    company: 'Dhuri Na Venture Private Limited',
    designation: 'Assistant Manager',
    startDate: '2022-01',
    endDate: null,
    isCurrent: true,
    responsibilities: [
      'Lead data analytics initiatives for business decision-making',
      'Design and maintain Power BI dashboards for operational reporting',
      'Automate repetitive workflows using Python and AI-assisted tools',
      'Collaborate with cross-functional teams to define data requirements',
      'Build and maintain web applications for internal operations',
      'Implement AI-enabled productivity workflows across teams',
    ],
    projects: [
      'Executive Dashboard - Real-time KPI monitoring',
      'Sales Analytics Pipeline - Automated data processing',
      'Operations Portal - Next.js web application',
      'AI-Assisted Reporting System - automated compilation with human review checkpoints',
    ],
    technologies: ['Python', 'SQL', 'Power BI', 'Excel', 'Power Query', 'DAX', 'Next.js', 'React', 'Supabase', 'PostgreSQL', 'Tailwind CSS', 'AI Tools'],
    description:
      'As Assistant Manager, I bridge business requirements with technical solutions. My role combines data analytics, business intelligence, web development, and AI-enabled automation to drive operational efficiency and data-driven decision making.',
    order: 1,
    status: 'published',
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
  {
    id: 'fallback-exp-2',
    company: 'MAS Educative',
    designation: '[ADD EXACT DESIGNATION]',
    startDate: '[ADD START DATE]',
    endDate: '[ADD END DATE]',
    isCurrent: false,
    responsibilities: ['[ADD VERIFIED RESPONSIBILITY 1]', '[ADD VERIFIED RESPONSIBILITY 2]'],
    projects: ['[ADD PROJECT 1]'],
    technologies: ['[ADD TECHNOLOGY 1]'],
    description: '[ADD ROLE DESCRIPTION]',
    order: 2,
    status: 'draft',
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
];

export const FALLBACK_SKILLS: Skill[] = [
  { id: 'fallback-skill-python', name: 'Python', category: 'data-analytics', proficiency: 'core', description: 'Data analysis, automation, scripting', order: 1, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-pandas', name: 'Pandas', category: 'data-analytics', proficiency: 'core', description: 'Data manipulation and analysis', order: 2, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-sql', name: 'SQL', category: 'data-analytics', proficiency: 'core', description: 'Querying, optimization, data modeling', order: 3, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-powerbi', name: 'Power BI', category: 'data-analytics', proficiency: 'core', description: 'Dashboard development, DAX, data visualization', order: 4, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-excel', name: 'Excel', category: 'data-analytics', proficiency: 'core', description: 'Advanced formulas, Power Query, modeling', order: 5, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-powerquery', name: 'Power Query', category: 'data-analytics', proficiency: 'applied', description: 'Data transformation and ETL', order: 6, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-dax', name: 'DAX', category: 'data-analytics', proficiency: 'applied', description: 'Data Analysis Expressions for Power BI', order: 7, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-sheets', name: 'Google Sheets', category: 'data-analytics', proficiency: 'applied', description: 'Collaborative analysis, Apps Script', order: 8, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-looker', name: 'Looker Studio', category: 'data-analytics', proficiency: 'working-knowledge', description: 'Dashboard creation and sharing', order: 9, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-nextjs', name: 'Next.js', category: 'web-development', proficiency: 'core', description: 'Full-stack React framework, App Router', order: 1, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-react', name: 'React', category: 'web-development', proficiency: 'core', description: 'Component architecture, hooks, state management', order: 2, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-ts', name: 'TypeScript', category: 'web-development', proficiency: 'core', description: 'Type-safe development', order: 3, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-html', name: 'HTML', category: 'web-development', proficiency: 'core', description: 'Semantic markup, accessibility', order: 4, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-css', name: 'CSS', category: 'web-development', proficiency: 'core', description: 'Modern CSS, animations, layouts', order: 5, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-tailwind', name: 'Tailwind CSS', category: 'web-development', proficiency: 'core', description: 'Utility-first styling', order: 6, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-supabase', name: 'Supabase', category: 'web-development', proficiency: 'applied', description: 'Backend-as-a-service, auth, database', order: 7, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-postgres', name: 'PostgreSQL', category: 'web-development', proficiency: 'applied', description: 'Relational database design, queries', order: 8, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-aidev', name: 'AI-Assisted Development', category: 'ai-automation', proficiency: 'core', description: 'Code generation, debugging, architecture', order: 1, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-prompt', name: 'Prompt Engineering', category: 'ai-automation', proficiency: 'core', description: 'Structured prompting for consistent results', order: 2, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-aidata', name: 'AI-Assisted Data Analysis', category: 'ai-automation', proficiency: 'applied', description: 'Automated insights, pattern detection', order: 3, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-aiworkflows', name: 'AI-Powered Workflows', category: 'ai-automation', proficiency: 'applied', description: 'Process automation with LLMs', order: 4, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-aicontent', name: 'AI Content Generation', category: 'ai-automation', proficiency: 'applied', description: 'Technical writing, documentation', order: 5, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-automation', name: 'Workflow Automation', category: 'ai-automation', proficiency: 'applied', description: 'End-to-end process automation', order: 6, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-canva', name: 'Canva', category: 'creative-technology', proficiency: 'core', description: 'Design, presentations, brand assets', order: 1, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-figma', name: 'Figma', category: 'creative-technology', proficiency: 'applied', description: 'UI/UX design, prototyping, design systems', order: 2, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-photoshop', name: 'Photoshop', category: 'creative-technology', proficiency: 'working-knowledge', description: 'Image editing, compositing', order: 3, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-aigraphic', name: 'AI Graphic Design', category: 'creative-technology', proficiency: 'applied', description: 'Midjourney, DALL-E, generative design', order: 4, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-aivideo', name: 'AI Video Creation', category: 'creative-technology', proficiency: 'working-knowledge', description: 'Runway, Sora, video generation', order: 5, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
  { id: 'fallback-skill-videoedit', name: 'Video Editing', category: 'creative-technology', proficiency: 'working-knowledge', description: 'Premiere Pro, DaVinci Resolve', order: 6, isActive: true, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
];

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: 'fallback-project-1',
    name: 'Portfolio Website',
    category: 'web-applications',
    problem: 'Need a professional, recruiter-first portfolio to showcase skills, experience, and projects with a self-managed CMS.',
    approach: 'Built a full-stack Next.js application with Supabase backend, featuring an admin panel for content management without code changes.',
    solution: 'Modern portfolio with hero, about, experience, skills, projects, resume, and contact sections. Admin dashboard with draft/preview/publish workflow.',
    role: 'Full-Stack Developer',
    technologies: ['Next.js 16', 'React 19', 'TypeScript', 'Supabase', 'PostgreSQL', 'Tailwind CSS', 'Radix UI'],
    keyFeatures: [
      'Secure admin panel with Supabase Auth',
      'Draft → Preview → Publish workflow',
      'Project/Experience/Skills/Profile management',
      'Resume upload and versioning',
      'SEO management',
      'Responsive, accessible design',
    ],
    outcome: 'Full-stack portfolio with a self-managed content system. GitHub workflow in place; production build verified and deployment-ready.',
    githubUrl: '[ADD GITHUB URL]',
    liveDemoUrl: '[ADD LIVE DEMO URL]',
    caseStudyUrl: '[ADD CASE STUDY URL]',
    thumbnail: '[ADD THUMBNAIL URL]',
    screenshots: [],
    isFeatured: true,
    status: 'published',
    order: 1,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
  {
    id: 'fallback-project-2',
    name: 'Executive Dashboard',
    category: 'data-analytics',
    problem: 'Leadership lacked real-time visibility into key business metrics across departments.',
    approach: 'Designed and built a Power BI dashboard connected to multiple data sources with automated refresh.',
    solution: 'Interactive dashboard with KPI tracking, drill-through capabilities, and role-based access.',
    role: 'Data Analyst / BI Developer',
    technologies: ['Power BI', 'DAX', 'Power Query', 'SQL', 'PostgreSQL'],
    keyFeatures: [
      'Real-time KPI monitoring',
      'Department-level drill-down',
      'Automated data refresh',
      'Role-based security',
      'Mobile-responsive layout',
    ],
    outcome: 'Interactive dashboard design with KPI tracking, drill-through capabilities, and role-based access for leadership visibility.',
    githubUrl: '',
    liveDemoUrl: '',
    caseStudyUrl: '[ADD CASE STUDY URL]',
    thumbnail: '[ADD THUMBNAIL URL]',
    screenshots: [],
    isFeatured: true,
    status: 'published',
    order: 2,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
  {
    id: 'fallback-project-3',
    name: 'AI-Assisted Reporting Automation',
    category: 'ai-automation',
    problem: 'Monthly business reports required 20+ hours of manual data compilation and formatting.',
    approach: 'Built an AI-powered pipeline using Python and LLMs to automate data extraction, analysis, and report generation.',
    solution: 'Automated workflow that pulls data, generates insights, and produces formatted reports with human review checkpoints.',
    role: 'Data Analyst / AI Automation Engineer',
    technologies: ['Python', 'OpenAI API', 'LangChain', 'Pandas', 'SQL', 'Power Automate'],
    keyFeatures: [
      'Automated data extraction from multiple sources',
      'AI-generated executive summaries',
      'Anomaly detection and flagging',
      'Human-in-the-loop validation',
      'Scheduled delivery via email/Teams',
    ],
    outcome: 'Automated workflow that pulls data, generates insights, and produces formatted reports with human review checkpoints.',
    githubUrl: '[ADD GITHUB URL]',
    liveDemoUrl: '',
    caseStudyUrl: '[ADD CASE STUDY URL]',
    thumbnail: '[ADD THUMBNAIL URL]',
    screenshots: [],
    isFeatured: true,
    status: 'published',
    order: 3,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
  {
    id: 'fallback-project-4',
    name: 'Operations Portal',
    category: 'web-applications',
    problem: 'Internal teams used disconnected spreadsheets and manual processes for daily operations.',
    approach: 'Developed a centralized Next.js web application with Supabase backend for workflow management.',
    solution: 'Multi-role application with task management, data entry forms, approval workflows, and reporting.',
    role: 'Full-Stack Developer',
    technologies: ['Next.js', 'React', 'TypeScript', 'Supabase', 'PostgreSQL', 'Tailwind CSS', 'Radix UI'],
    keyFeatures: [
      'Role-based access control',
      'Dynamic form builder',
      'Approval workflow engine',
      'Real-time notifications',
      'Audit logging',
      'Export to Excel/PDF',
    ],
    outcome: 'Centralized application with task management, data entry forms, approval workflows, and reporting for daily operations.',
    githubUrl: '[ADD GITHUB URL]',
    liveDemoUrl: '[ADD LIVE DEMO URL]',
    caseStudyUrl: '[ADD CASE STUDY URL]',
    thumbnail: '[ADD THUMBNAIL URL]',
    screenshots: [],
    isFeatured: true,
    status: 'published',
    order: 4,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
  {
    id: 'fallback-project-5',
    name: 'Sales Analytics Pipeline',
    category: 'data-analytics',
    problem: 'Sales data scattered across CRM, ERP, and spreadsheets made trend analysis difficult.',
    approach: 'Built an automated ETL pipeline using Python and SQL to consolidate data into a unified warehouse.',
    solution: 'Scheduled data pipeline with data quality checks, transformation logic, and Power BI integration.',
    role: 'Data Engineer / Analyst',
    technologies: ['Python', 'SQL', 'Pandas', 'PostgreSQL', 'Power BI', 'Airflow'],
    keyFeatures: [
      'Automated daily ETL',
      'Data quality validation',
      'Incremental loading',
      'Error alerting',
      'Historical snapshots',
      'Self-service analytics layer',
    ],
    outcome: 'Unified data pipeline with quality checks, transformation logic, and Power BI integration for trend analysis.',
    githubUrl: '[ADD GITHUB URL]',
    liveDemoUrl: '',
    caseStudyUrl: '[ADD CASE STUDY URL]',
    thumbnail: '[ADD THUMBNAIL URL]',
    screenshots: [],
    isFeatured: false,
    status: 'published',
    order: 5,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
  {
    id: 'fallback-project-6',
    name: 'AI Content Generation Toolkit',
    category: 'ai-automation',
    problem: 'Content creation for marketing, documentation, and training was time-consuming and inconsistent.',
    approach: 'Developed a set of structured prompts and workflows using LLMs for various content types.',
    solution: 'Reusable prompt library with templates for technical docs, marketing copy, training materials, and code documentation.',
    role: 'AI Workflow Designer',
    technologies: ['Prompt Engineering', 'Claude/GPT-4', 'Notion', 'Python', 'Markdown'],
    keyFeatures: [
      'Structured prompt templates',
      'Consistent output formatting',
      'Version-controlled prompts',
      'Integration with Notion',
      'Quality scoring rubric',
    ],
    outcome: 'Reusable prompt library with templates for technical docs, marketing copy, training materials, and code documentation.',
    githubUrl: '[ADD GITHUB URL]',
    liveDemoUrl: '',
    caseStudyUrl: '[ADD CASE STUDY URL]',
    thumbnail: '[ADD THUMBNAIL URL]',
    screenshots: [],
    isFeatured: false,
    status: 'published',
    order: 6,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
];